= Cassey Low - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Infinity Machine

---

== Overview

Infinity Machine is a desktop source manager application used for storing research data. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added *the ability to restore previous deleted sources*
** What it does: allows the user to restore all previously deleted sources one at a time. Preceding restore commands can be reversed by using the redo command.
** Justification: This feature improves the product significantly because a user leave the application safely even if they accidentally deleted an important research data or if their computer accidentally crashes. This cannot be achieved with the current undo command because it would be inefficient to undo the commands other than the delete sources and undo is not persistent.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands as well as almost every component in the application.
** Credits: Referenced and Analysed how AddressBook4's json data was implemented so that it can be used to implement the persistent storage for DeletedSources.

* *Minor enhancement*: added a count command that allows the user to count the sources in the list retrieved from the database.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.1` - `v1.3` (all 3 releases so far) on GitHub
** Enhancements to existing features:
*** Refactored and fixed many parts of the application so that it can be used for Infinity Machine(Pull requests https://github.com/CS2103-AY1819S2-W13-3/main/pull/106)
*** Wrote and fixed tests for existing features as well as Failing Tests and SystemTests when Refactoring (Pull requests https://github.com/CS2103-AY1819S2-W13-3/main/issues/112)
*** Helped to write releases for v1.1 - v1.3
** Documentation:
*** Write features section of the User Guide:
** Community:
*** PRs reviewed (with non-trivial review comments): many PRs reviewed
*** Contributed to forum discussions (examples:  asked questions)
*** Reported bugs and suggestions for other teams in the class (examples:)

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=undoredo]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
