= Darren Lee Wei Sheng - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: The Infinity Machine

---

== Overview

The Infinity Machine is a desktop application that lets users store research materials for future use. It provides a quick and easy way for tech-savvy users, like university students or researchers, to manage and organise their research materials.

The user interacts with the application using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major Enhancement*: Added the Pin command set to the application
** What it does: This function allows for greater organisational capability by letting users pin important or frequently viewed sources to the top of the application.
** Justification: This feature improves the product significantly because it gives users a fast and efficient way to make important sources more visible at the top. Critical sources can be immediately moved to the top while older or outdated sources will be pushed to the bottom of the list.
** Implementation: This new feature required additional model functionality which needed to be added and tested thoroughly before deployment. Furthermore, it also required persistent storage of pinned sources so that users will be able to preserve their pinned sources. This required the implementation of additional storage functionality.

* *Minor Enhancement*: Added the Custom Order command to the application
** What it does: This function allows greater flexibility and personalisation for the application by giving users manual control over the order of which they want their sources to appear.
** Justification: This feature improves the product significantly because it allows users greater customisation options for their own personal sources which enhances the management and organisation component of the application. Critical sources can be given priority and be moved to the top while older or outdated sources can be relegated to the bottom of the list.
** Implementation: This new feature utilised the additional model functionality from the pin command but still required thorough testing before deployment.

* *Code contributed*: [https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#=undefined&search=darrendragonlee[Project Dashboard]]

* *Other contributions*:

** Project management:
*** Managed and maintained the team's AboutUs page, ensuring images, names and links are up to date (Pull Requests https://github.com/CS2103-AY1819S2-W13-3/main/pull/43[#43], https://github.com/CS2103-AY1819S2-W13-3/main/pull/58[#58], https://github.com/CS2103-AY1819S2-W13-3/main/pull/61[#61])

** Model development:
*** Designed and implemented a brand new model for research sources based on the original AddressBook implementation (Pull Requests https://github.com/CS2103-AY1819S2-W13-3/main/pull/54[#54], https://github.com/CS2103-AY1819S2-W13-3/main/pull/69[#69])
**** Ultimately unused in the final version of the application but was important in guiding the reintegration of the final source model

** Integration of existing functions:
*** Updated the existing add and edit commands to be able to incorporate research sources (Pull request https://github.com/CS2103-AY1819S2-W13-3/main/pull/88[#88])
**** Refactored a significant amount of code to ensure functionality across the entire model

** Feature Enhancements
*** Enhanced the Add and Edit functions to include a new Author field which made sources more comprehensive (Pull request https://github.com/CS2103-AY1819S2-W13-3/main/pull/218[#218])
**** Allowed for additional functionality like the bibliographical generation
*** Enhanced the Tags for sources to be able to include spaces for multi-word tags (https://github.com/CS2103-AY1819S2-W13-3/main/pull/220[#220], https://github.com/CS2103-AY1819S2-W13-3/main/pull/221[#221])
**** Tags initially included special characters as well but was later narrowed down to just letters, numbers and spaces as special characters were deemed unnecessary for tags.

** Test Enhancements
*** Added hashcode overrides to numerous existing features to ensure compliance with the hashcode contract (Pull request https://github.com/CS2103-AY1819S2-W13-3/main/pull/203[#203])
**** Incorporated comprehensive tests for said function to check for non-compliance if any

** Documentation:
*** Made comprehensive overall updates to the User Guide which made it more accurate and inclusive (Pull request https://github.com/CS2103-AY1819S2-W13-3/main/pull/133[#133])
*** Added a section on User Stories to the Developer Guide to better direct the development of the application (Pull request https://github.com/CS2103-AY1819S2-W13-3/main/pull/125[#125])
*** Added a large section encompassing all the use cases for every function in the application to the Developer Guide to assist in testing the functions for the correct outputs (Pull request https://github.com/CS2103-AY1819S2-W13-3/main/pull/134[#134])

** Community:
*** Offered technical assistance to team mates by providing in depth code analysis for pull requests (Pull request https://github.com/CS2103-AY1819S2-W13-3/main/pull/128[#128], https://github.com/CS2103-AY1819S2-W13-3/main/pull/203[#203], https://github.com/CS2103-AY1819S2-W13-3/main/pull/219[#219])

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=order]

include::../UserGuide.adoc[tag=add]

include::../UserGuide.adoc[tag=edit]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=devorder]
