= Ruhani Suri - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: The Infinity Machine

---

== Overview

"To understand matters rightly we should understand their details; and as that knowledge is almost infinite, our knowledge
is always superficial and imperfect." - Francois de La Rochefoucauld

The knowledge in the universe is infinite and there exists many things that are still beyond our comprehension. However,
that does not mean that the process of learning what we have discovered should be a difficult one.

Introducing the Infinity Machine, an application for efficient storing and retrieving of textual information on research
material by allowing users to apply to it custom made tags and type for easy search and retrieval. Intended for tech-savvy
university students who are able to use CLI and wish to organize and tag research information or any other data that they
may wish to store.

No longer will you miss out on important sources or developments in your field of interest.  No longer will you forget
where you read something and struggle to find it again.

== Summary of contributions

=== *Major enhancement*: +

===== 1. Modified *the ability to search* through sources:

====== *Previously*:

Format: `search <title>`

In the given codebase of AB4, the `search` command could only take one type of arguments, of title type, and listed all
sources that have one of those titles present in them.
This search was case-insensitive.

For example, when a user executes the command `search algorithm`, all those sources which have the
title of 'algorithm' (or any of the case combination) will be populated on the GUI, with all their details
such as their titles, types, details and tags. This list will be indexed (numbered). Only exact matches are\
considered.

This provides the users with limited functionality as they are only able to search through the sources by their titles.
Ideally, we would want to give the user a more powerful search function that allows them to search through the sources
with more fields and parameters, for example used in conjunction.

====== *Modification*:

Format: `search [n/TITLE] [y/TYPE] [d/DETAILS] [t/TAG] [t/TAG]...`

In the implementation of The Infinity Machine, search function now has an added functionality of being able to take in multiple
arguments of the type of source fields, and search for sources based on that.
It searchs in conjunction using multiple fields including title, type, detail and tag(s) input by the user,
listing only those sources that satisfy all the input constraints of the matching fields.

====== *What it does*:
It allows the user to search through all the entries in the database through various fields at a time, and display
source entries that satisfy all of the entered tags in conjunction.
It allows compound searches to be made, allowing user to narrow down their search, hence helping in efficient retrieval
of the sources, and making working on the database more efficient.

====== *Justification*:
This feature improves the product significantly because a user can now search an entry with a particular title AND a particular type and so on.
It helps user greatly narrow down their search should they be looking for a specific source entry with particular values,
instead of cluttering the screen with all those sources with share the same title as the one the user searches using the command.
It also allows user to search sources based on other fields and not just title, such as type, tags and details, and even their
logical combination.

====== *Highlights*:
- This enhancement does not affect existing commands and commands to be added in future.
- However, it changed the format of the original `search` command, which now not only takes parameters of different types, but also needs them to be prefixed by their
CLI delimiters.
- It required an in-depth analysis of design alternatives, as the format of the original command had to be changed
- The implementation too was challenging, as the current format of `search` command had to be changed and be prepared to
accept and parse multiple fields entered.
- Its was also tricky to implement the conjunction of the fields as separate methods had to be written for checking for the presence
of each of the field entered and by logical `&&` ing their results.

====== *Credits*:
Most of the feature was developed independently, with some design and implementation considerations discussed with fellow team members.

=== *Minor enhancement*:

==== 1. Modified *the ability to list* sources:

===== *Previously*:
Format: `list`

In AB4, `list` command was a very useful feature which displayed to the user all the sources present in the database.
The list command by default displayed all the sources in the order of least recently added first and displayed along with it
all the details of the source, such as title, type, detail and tags.

For example, when the user executes `list`, we see the updated list of all the source and their fields.

===== *Modification*:
Format: `list [n]`
inside [] means optional

However, one may feel that such act of populating *all* the sources on the GUI may be cluttering the view unnecessarily.
Now, what could be the parameters a user may want to limit the list by? Limiting merely by their field values is akin to search,
which would make the logic redundant. In contrast, the user may want to control the number of sources he wants to view.
This could be helpful in:

1. Iteratively examining all the sources by restricting how many are shown at one time.
2. Making more effective use of the GUI display to the user by not unnecessarily enumerating all sources.

Thus, the new modification to the command changes its format optionally, allowing user to be able to pass a parameter
and list only those many sources from the top, that is from the least-recently added. This may be intuitively useful when say
you want to perform certain operations in this new list of sources that are displayed by their time of addition.
Example, a user wants to delete all of the sources that were added yesterday. And if 10 entries were added yesterday,
the user could just execute `list 10` to access
those entries and then perform a `delete <INDEX>` accordingly.

For example, the user may still execute `list` command to see the updated list of all the source and their fields.

But now, one may also enter `list 21` to list the top 21 sources only, allowing user to streamline their retrieval for more
efficient operations on the sources.

===== *What it does*:
It allows the user to now pass an optional argument to `list` command, a positive integer n, and then displays only the first n source entries.
The original working of the `list` command showing all entries is still intact, thus just appending extra functionality without
changing the original logic.

===== *Justification*:
This feature improves the product significantly because a user can now list only as many item he wants and need not clutter the screen by displaying all.
It helps him to narrow down his search, say should he want to view the N first added sources. This ensures more effective retrieval and
operations on the sources, such as following it by index dependent operations such as `edit` and `delete` for instance.

===== *Highlights*:
- This enhancement does not affect existing commands and commands to be added in future.
- It required an in-depth analysis of design alternatives. Especially when it came to adding the ability
for the command to be able to work both with 1 parameter and no parameters.
Some design considerations were
** Using variable arguments: in `parser` method of `ListCommandParser` class, but this would require changing the
Interface `Parser<T>`. This technique did not work for making `ListCommand` objects for the same reason.
** Using method overloading: This did not work for `parser` method because of the interface restrictions, however
this was used in the constructor of `LogicCommand` class, creating two objects depending on whether a `targetIndex` was passed
or not.
** Using args.length(): Ultimately used in `parse` method for a simple check whether an
argument is passed or not.
- The implementation too was challenging, as the current format of `list` command had to be changed and be prepared to accept and parse an optional argument, ie. overloading
functionality based on whether an argument was passed by the user or not.

===== *Credits*:
Most of the feature was developed independently, with some design and implementation considerations discussed with fellow team members.

=== *Code contributed*:
[https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#search=suriruhani&sort=displayName&since=2019-02-10&until=2019-04-02&timeframe=day&reverse=false&repoSort=true[Reposense contribution]] +
[https://github.com/CS2103-AY1819S2-W13-3/main/blob/master/src/main/java/seedu/address/logic/commands/SearchCommand.java[search command code]] +
[https://github.com/CS2103-AY1819S2-W13-3/main/blob/master/src/test/java/seedu/address/logic/commands/SearchCommandTest.java[search command test]] +
[https://github.com/CS2103-AY1819S2-W13-3/main/blob/master/src/main/java/seedu/address/logic/commands/ListCommand.java[list command code]] +
[https://github.com/CS2103-AY1819S2-W13-3/main/blob/master/src/test/java/seedu/address/logic/commands/ListCommandTest.java[list command test]] +

=== *Other contributions*:

==== Project management:
*** Helped in maintaining issue tracker and milestone progress, along with managing project releases and reviewing and merging
pull requests.
*** Helped in refactoring Storage AP in migrating the codebase from AB4 to The Infinity Machine for our team, helped in refactoring the entire Storage package
to be compatible with the functionalities required by our application, mostly changing identifier names and method signatures to model
our application's scope.

==== Enhancements to existing features:
*** Fixed failing test cases of AB4 to accommodate the modified command formats, for both `search` and `list`.
*** Adding relevant test cases for both `search` and `list` to test the various use cases of the commands and specifcally
some problematic edge cases.
***  Enhanced javadocs for implemented methods to make their functionality and logic more
relevant to our application's scope, changing parameter and return type along with modifying format and functionality explanation.

==== Documentation:
*** Added to and updated the User Guide
*** Added to and updated the Developer Guide
*** Added to and updated the ContactUs.adoc
*** Added to and updated the AboutUs.adoc

==== Community:
*** Reviewed and approved PRs of other team mates
*** Helped in tracking issues including assigning severity, status, type, and closing it.

//==== Tools:

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=list]

include::../UserGuide.adoc[tag=search]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=list]

include::../DeveloperGuide.adoc[tag=search]

---
//== PROJECT: PowerPointLabs
//
//---
//
//_{Optionally, you may include other projects in your portfolio.}_
