= The Infinity Machine - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/CS2103-AY1819S2-W13-3/main

By: `Team SE-EDU`      Since: `Jun 2016`      Licence: `MIT`

== Introduction

"To understand matters rightly we should understand their details; and as that knowledge is almost infinite, our knowledge is always superficial and imperfect." - Francois de La Rochefoucauld

The knowledge in the universe is infinite and there exists many things that are still beyond our comprehension. However, that does not mean that the process of learning what we have discovered should be a difficult one.

Introducing the Infinity Machine, an application for efficient storing and retrieving of textual information on research material by allowing users to apply to it custom made tags and type for easy search and retrieval. Intended for tech-savvy university students who are able to use CLI and wish to organize and tag research information or any other data that they may wish to store.

No longer will you miss out on important sources or developments in your field of interest.  No longer will you forget where you read something and struggle to find it again.

== Quick Start

.  Ensure you have Java version `9` or later installed in your Computer.
.  Download the latest `infinitymachine.jar` link:{repoURL}/releases[here].
.  Copy the file to the folder you want to use as the home folder for your Infinity Machine.
.  Double-click the file to start the app. The GUI should appear in a few seconds.
.  Type the command in the command box and press kbd:[Enter] to execute it. +
e.g. typing *`help`* and pressing kbd:[Enter] will open the help window.
.  Some example commands you can try:

* *`list`* : lists all sources currently in the Infinity Machine
* **`add`**`i/Algorithms Wikipedia y/Website d/Basic definitions and history of algorithms t/Algorithms t/Computer Science` : adds a source named `Wikipedia Algorithms` to the Infinity Machine.
* **`delete`**`3` : deletes the 3rd source shown in the current list
* *`exit`* : exits the the Infinity Machine

.  Refer to <<Features>> for details of each command.

[[Features]]
== Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `add n/TITLE`, `TITLE` is a parameter which can be used as `add n/Wikipedia Algorithms`.
* Items in square brackets are optional e.g `n/TITLE [t/TAG]` can be used as `n/Wikipedia Algorithms t/Wikipedia` or as `n/Wikipedia Algorithms`.
* Items with `…`​ after them can be used multiple times including zero times e.g `[t/TAG]...` can be used as `{nbsp}` (i.e. 0 times), `t/Computer Science`, `t/Computer Science t/Algorithms` etc.
* Parameters can be in any order e.g. if the command specifies `i/TITLE y/TYPE`, `y/TYPE i/TITLE` is also acceptable.
====

=== Viewing help : `help`

Format: `help`

// tag::add[]
=== Adding a person: `add`

Adds a new source to the list of sources +
Format: `add n/TITLE y/TYPE d/DETAILS [t/TAG]...`

[TIP]
A source can have any number of tags (including 0)

Examples:

* `add i/Algorithms Wikipedia y/Website d/Basic definitions and history of algorithms t/Algorithm t/Wikipedia`
* `add i/Artificial Intelligence IEEE y/Journal Article d/introductory facts on artificial intelligence t/Science Journal t/AI`
// end::add[]

=== Deleting a source : `delete`

Deletes the specified source. +
Format: `delete INDEX`

****
* Deletes the source at the specified `INDEX`.
* The index refers to the index number shown in the displayed source list.
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `list` +
`delete 2` +
Deletes the 2nd source in the database.
* `search algorithms` +
`delete 1` +
Deletes the 1st source in the results of the `find` command.

// tag::edit[]
=== Editing a source : `edit`

Edits an existing source in the database. +
Format: `edit INDEX [i/TITLE] [y/TYPE] [d/DETAILS] [t/TAG]...`

****
* Edits the source at the specified `INDEX`. The index refers to the index number shown in the displayed source list. The index *must be a positive integer* 1, 2, 3, ...
* At least one of the optional fields must be provided.
* For the editing of tags, any existing tags to be kept must be re-entered.
* If the existing tags are `Algorithm` and `Wikipedia` and the user wants to keep only `Algorithm`, they must enter the command `edit 1 t/Algorithm`.
* Entering just `t/` without any thing after that will simply delete all tags for that entry.
****

Examples:

* `edit 2 n/Photosynthesis Wikipedia t/Photosynthesis t/Biology` +
Edits the title and tags of the source to be `Photosynthesis Wikipedia` and `Photosynthesis, Biology` respectively.
* `edit 5 t/` +
Edits the 5th source and clears all its existing tags.
// end::edit[]

=== Searching a source: `search`

Searches for entries amongst the list of sources by title. +
Finds all entries with an (exact, case insensitive) matching title as entered by the user. +
It is case insensitive (eg. `RSAalgorithm` is same as `rsaalgorithm`) +
Matching is exact (eg. `Algorithm` will not match with `Algorithms`) +
Format: `search title`

****
* The search is case insensitive. e.g `hans` will match `Hans`
* There can have any number of tags but minimally 1 (just `search` results in error. To enumerate all entries, check out `list` command instead)
* Only full words will be matched e.g. `Han` will not match `Hans`, `FooTitle` will not match `FooTitle1`
****

Examples:

* `search Algorithms` +
Returns the source with the title `algorithms`
* `search ArtificialIntelligence MachineLearning` +
Returns any source having tags `ArtificialIntelligence` or `MachineLearning`

=== Listing all sources : `list [n]`

Displays a list of all sources currently in the database, without filtering. +
Optional argument N used to list only the top N sources to the user. +
Format: `list [N]`

****
* Lists all sources present in the database in the order of their addition, if no argument passed
* Lists top N sources if a single integer N is passed
* Throws error if more than one arguments are passed
* The paramter passed, N, must be a positive integer else error is thrown
* Tags, Details, Type are also displayed along with the sources
****

// tag::order[]
=== Reordering sources to your liking : `order`

Moves the specified source from one position to another as defined by the user. +
Format: `delete ORIGINAL_INDEX NEW_INDEX`

****
* Obtains the source at the specified `ORIGINAL_INDEX` and moves it to the `NEW_INDEX`.
* The index refers to the index number shown in the displayed source list.
* The index *must be a positive integer* 1, 2, 3, ...
* The specified source will replace the original source at that index.
** If the souce was shifted forward, sources before the `NEW_INDEX` will be shifted back and the source designated by `ORIGINAL_INDEX` will take the position of `NEW_INDEX`.
** If the souce was shifted backwards, sources after the `NEW_INDEX` will be shifted forward and the source designated by `ORIGINAL_INDEX` will take the position of `NEW_INDEX`.
****

Examples:

* `order 1 4` +
Moves the source located at index 1 to index 4.

* `order 1 6` +
If there are only 6 sources in the database, the command moves the source located at index 1 to last position in the list.
// end::order[]

=== Generate bibliography entry : `biblio`

Generates an bibliographical entry from the source at the specified. +
Format: `biblio INDEX`

****
* Generates a bibliographical entry from the source at the specified `INDEX`.
* The index refers to the index number shown in the displayed source list.
* The index *must be a positive integer* 1, 2, 3, ...
****

=== Listing entered commands : `history`

Lists all the commands that you have entered in reverse chronological order. +
Format: `history`

=== Listing history of searches made : `searchhistory`

Lists the results of all searches made using the `search` command recently. +
Format: `searchhistory`

=== Command aliases : `alias`
==== Creating an alias: `alias`
Allows the user to create aliases create aliases for commands. +
Format: `alias COMMAND ALIAS`

Examples:

* `alias count c` (`c` is now a valid pseudo-command that works exactly like `count`)
* `alias invalid i` (`i` is now an invalid pseudo-command that works exactly like `invalid`)

The user is responsible for ensuring that he is creating aliases for valid commands.
The successful creation of an alias does not provide any guarantee of the validity of the associated command.

If the user attempts to add an alias that has already been added, the old one will be overwritten. For example:

* `alias count c`
* `alias invalid c`

`c` is now an alias for the invalid command `invalid`.

The command may not be another alias. The alias may not be a command.

* `alias count ct` (`ct` is now an alias for `count`)
* `alias ct c` (this is invalid because `ct` is another alias)
* `alias count list` (this is invalid because `list` is a command)

The alias must be syntatically valid. A valid syntax may only contain alphabets.

* `alias list l` (valid)
* `alias count ct` (valid)
* `alias clear $` (invalid)

==== Removing an alias: `alias-rm`
Allows the user to remove previously-defined aliases. +
Format: `alias-rm ALIAS`

Examples:

* `alias count c` (`c` is now an alias for `count`)
* `alias-rm c` (`c` is no longer an alias for `count`)

If the user attempts to remove a non-existent alias, nothing happens.
`alias-rm` only guarantees that after it is performed, the alias argument does not exist.

==== Listing all aliases: `alias-ls`
Lists all defined aliases and their associated commands. +
Format: `alias-ls`

==== Alias persistence
Aliases are persistent across usage sessions.
When an alias is created or removed, this is recorded to disk.
No action is required on the user's part.

=== Counting total number of sources: `count`

Counts and returns the total number of source entries retrieved. +
Format: `count`

Examples:

* `count` +
Result: `Total number of source(s): 6` +
Counts the total number of sources retrieved from the database.

// tag::undoredo[]
=== Undoing previous command : `undo`

Allows the user to reverse the last performed undoable action. +
Format: `undo`

[NOTE]
====
Undoable commands: those commands that modify the source's content (`add`, `delete`, `edit` and `clear`).
====

Examples:

* `delete Algorithms` +
`list` +
`undo` (reverses the `delete Algorithms` command) +

* `select 1` +
`list` +
`undo` +
The `undo` command fails as there are no undoable commands executed previously.

* `delete 1` +
`clear` +
`undo` (reverses the `clear` command) +
`undo` (reverses the `delete 1` command) +

=== Redoing the previously undone command : `redo`

Allows user to redo the last performed action. +
Format: `redo`

Examples:

* `delete 1` +
`undo` (reverses the `delete 1` command) +
`redo` (reapplies the `delete 1` command) +

* `delete 1` +
`redo` +
The `redo` command fails as there are no `undo` commands executed previously.

* `delete 1` +
`clear` +
`undo` (reverses the `clear` command) +
`undo` (reverses the `delete 1` command) +
`redo` (reapplies the `delete 1` command) +
`redo` (reapplies the `clear` command) +
// end::undoredo[]

=== Enabling panic mode : `panic`

Allows user to temporarily hide data. +
Format: `panic`

=== Enabling panic mode : `unpanic`

Restores user data. +
Format: `unpanic`

=== Clearing all entries : `clear`

Clears all entries from the address book. +
Format: `clear`

=== Exiting the program : `exit`

Exits the program. +
Format: `exit`

=== Autocorrect ('Did you mean') : <no command>

Suggests commands to the users when they get the spelling wrong. +

Examples:

* `delete Algorith` +
`Did you mean: Algorithms`

=== Saving the data

Address book data are saved in the hard disk automatically after any command that changes the data. +

There is no need to save manually.

// tag::dataencryption[]
=== Encrypting data files `[coming in v2.0]`

Research materials can be very sensitive and private especially for high profile researchers. The Infinity Machine hopes to be able to help researchers by encrypting their data for only authorised viewers to access.

Will allow users to generate simple encryption keys which will help keep their research materials secure.
// end::dataencryption[]

== FAQ

*Q*: How do I transfer my data to another Computer? +
*A*: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous Infinity Machine folder.

== Command Summary

* *Add* `add i/TITLE y/TYPE d/DETAILS [t/TAG]...` +
e.g. `add i/Artificial Intelligence IEEE y/Journal Article d/Landmark paper on perils of artificial intelligence t/Science Journal t/AI`
* *Clear* : `clear`
* *Delete* : `delete INDEX` +
e.g. `delete 3`
* *Edit* : `edit INDEX i/TITLE y/TYPE d/DETAILS [t/TAG]...` +
e.g. `edit 2 i/Photosynthesis Wikipedia t/Photosynthesis t/Biology`
* *Search* : `search [KEYWORD] [KEYWORD]...` +
e.g. `search algorithm journal`
* *List* : `list`
* *Help* : `help`
* *Biblio* : `biblio`
* *History* : `history`
* *Search History* : `searchhistory`
* *Define Command* : `definecommand c/COMMAND a/ALIAS` +
e.g. `definecommand c/edit a/e`
* *Undo* : `undo`
* *Redo* : `redo`
* *Panic* : `panic`
* *Unpanic* : `unpanic`
