= The Infinity Machine - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/se-edu/addressbook-level4

By: `Team SE-EDU`      Since: `Jun 2016`      Licence: `MIT`

== Introduction

An application for efficient storing and retrieving of textual information on research material by allowing users to apply to it custom made tags and type for easy search and retrieval. Intended for tech-savvy university students who are able to use CLI and wish to organize and tag research information or any other data that they may wish to store.

== Quick Start

.  Ensure you have Java version `9` or later installed in your Computer.
.  Download the latest `addressbook.jar` link:{repoURL}/releases[here].
.  Copy the file to the folder you want to use as the home folder for your Address Book.
.  Double-click the file to start the app. The GUI should appear in a few seconds.
.  Type the command in the command box and press kbd:[Enter] to execute it. +
e.g. typing *`help`* and pressing kbd:[Enter] will open the help window.
.  Some example commands you can try:

* *`list`* : lists all contacts
* **`add`**`n/John Doe p/98765432 e/johnd@example.com a/John street, block 123, #01-01` : adds a contact named `John Doe` to the Address Book.
* **`delete`**`3` : deletes the 3rd contact shown in the current list
* *`exit`* : exits the app

.  Refer to <<Features>> for details of each command.

[[Features]]
== Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `add n/NAME`, `NAME` is a parameter which can be used as `add n/John Doe`.
* Items in square brackets are optional e.g `n/NAME [t/TAG]` can be used as `n/John Doe t/friend` or as `n/John Doe`.
* Items with `…`​ after them can be used multiple times including zero times e.g. `[t/TAG]...` can be used as `{nbsp}` (i.e. 0 times), `t/friend`, `t/friend t/family` etc.
* Parameters can be in any order e.g. if the command specifies `n/NAME p/PHONE_NUMBER`, `p/PHONE_NUMBER n/NAME` is also acceptable.
====

=== Viewing help : `help`

Format: `help`

=== Adding a person: `add`

Adds a new source to the list of sources +
Format: `add n/NAME p/TYPE s/SOURCE [t/TAG]...`

[TIP]
A source can have any number of tags (including 0)

Examples:

* `add n/Algorithms Wikipedia y/Website s/https://en.wikipedia.org/wiki/Algorithm t/Algorithm t/Wikipedia`
* `add n/Artificial Intelligence IEEE y/Journal Article s/IEEE t/Science Journal t/AI`

=== Deleting a source : `delete`

Deletes the specified source. +
Format: `delete INDEX`

****
* Deletes the source at the specified `INDEX`.
* The index refers to the index number shown in the displayed source list.
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `list` +
`delete 2` +
Deletes the 2nd source in the database.
* `search algorithms` +
`delete 1` +
Deletes the 1st source in the results of the `find` command.

=== Editing a source : `edit`

Edits an existing source in the database. +
Format: `edit INDEX [n/NAME] [p/PHONE] [e/EMAIL] [a/ADDRESS] [t/TAG]...`

****
* Edits the source at the specified `INDEX`. The index refers to the index number shown in the displayed source list. The index *must be a positive integer* 1, 2, 3, ...
* At least one of the optional fields must be provided.
* For the editing of tags, any existing tags to be kept must be re-entered.
* If the existing tags are `Algorithm` and `Wikipedia` and the user wants to keep only `Algorithm`, they must enter the command `edit 1 t/Algorithm`.
* Entering just `t/` without any thing after that will simply delete all tags for that entry.
****

Examples:

* `edit 2 n/Photosynthesis Wikipedia t/Photosynthesis t/Biology` +
Edits the title and tags of the source to be `Photosynthesis Wikipedia` and `Photosynthesis, Biology` respectively.
* `edit 5 t/` +
Edits the 5th source and clears all its existing tags.

=== Searching a source: `search`

Searches for entries amongst the list of sources based on the tag entered by the user. +
Format: `search t/TAG [t/TAG]...`

****
* The search is case insensitive. e.g `hans` will match `Hans`
* There can have any number of tags but minimally 1.
* Only full words will be matched e.g. `Han` will not match `Hans`
****

Examples:

* `search t/Algorithms` +
Returns the source with the tag `algorithms`
* `search t/Artificial Intelligence t/Science Journal t/AI` +
Returns any source having tags `Artificial Intelligence`, `Science Journal`, or `AI`

=== Listing all sources : `list`

Displays a list of all sources currently in the database. Also allows listing of all tags and types of records. +
Format: `list` `list tags` `list types`

=== Reordering sources to your liking : `order`

Moves the specified source from one position to another as defined by the user. +
Format: `delete ORIGINAL_INDEX NEW_INDEX`

****
* Obtains the source at the specified `ORIGINAL_INDEX` and moves it to the `NEW_INDEX`.
* The index refers to the index number shown in the displayed source list.
* The index *must be a positive integer* 1, 2, 3, ...
* All sources after the location moved to will be shifted downwards.
****

Examples:

* `order 1 4` +
Moves the source located at index 1 to index 4.

=== Generate bibliography entry : `biblio`

Allows user to generate bibliography using the links user entered as their sources. +
Format: `biblio`

Examples:

* `biblio https://en.wikipedia.org/wiki/Algorithm` +
Generates bibliography for Algorithms source.

=== Listing entered commands : `history`

Lists all the commands that you have entered in reverse chronological order. +
Format: `history`

=== Listing history of searches made : `searchhistory`

Lists the results of all searches made using the `search` command recently. +
Format: `searchhistory`

=== Define custom commands : `definecommand`

Allows the user to give aliases to frequently used verbose commands. +
Format: `definecommand c/COMMAND a/ALIAS`

Examples:
* `definecommand c/biblio a/b`

// tag::undoredo[]
=== Undoing previous command : `undo`

Allows the user to reverse the last performed undoable action. +
Format: `undo`

[NOTE]
====
Undoable commands: those commands that modify the source's content (`add`, `delete`, `edit` and `clear`).
====

Examples:

* `delete Algorithms` +
`list` +
`undo` (reverses the `delete Algorithms` command) +

* `select 1` +
`list` +
`undo` +
The `undo` command fails as there are no undoable commands executed previously.

* `delete 1` +
`clear` +
`undo` (reverses the `clear` command) +
`undo` (reverses the `delete 1` command) +

=== Redoing the previously undone command : `redo`

Allows user to redo the last performed action. +
Format: `redo`

Examples:

* `delete 1` +
`undo` (reverses the `delete 1` command) +
`redo` (reapplies the `delete 1` command) +

* `delete 1` +
`redo` +
The `redo` command fails as there are no `undo` commands executed previously.

* `delete 1` +
`clear` +
`undo` (reverses the `clear` command) +
`undo` (reverses the `delete 1` command) +
`redo` (reapplies the `delete 1` command) +
`redo` (reapplies the `clear` command) +
// end::undoredo[]

=== Enabling panic mode : `panic`

Allows user to temporarily hide data. +
Format: `panic`

=== Enabling panic mode : `unpanic`

Restores user data. +
Format: `unpanic`

=== Clearing all entries : `clear`

Clears all entries from the address book. +
Format: `clear`

=== Exiting the program : `exit`

Exits the program. +
Format: `exit`

=== Autocorrect ('Did you mean') : <no command>

Suggests commands to the users when they get the spelling wrong. +

Examples:

* `delete Algorith` +
`Did you mean: Algorithms`

=== Saving the data

Address book data are saved in the hard disk automatically after any command that changes the data. +
There is no need to save manually.

// tag::dataencryption[]
=== Encrypting data files `[coming in v2.0]`

_{explain how the user can enable/disable data encryption}_
// end::dataencryption[]

== FAQ

*Q*: How do I transfer my data to another Computer? +
*A*: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous Address Book folder.

== Command Summary

* *Add* `add n/NAME y/TYPE s/SOURCE [t/TAG]...` +
e.g. `add n/Artificial Intelligence IEEE y/Journal Article s/IEEE t/Science Journal t/AI`
* *Clear* : `clear`
* *Delete* : `delete INDEX` +
e.g. `delete 3`
* *Edit* : `edit INDEX n/NAME y/TYPE s/SOURCE [t/TAG]...` +
e.g. `edit 2 n/Photosynthesis Wikipedia t/Photosynthesis t/Biology`
* *Search* : `search [KEYWORD] [KEYWORD]...` +
e.g. `search algorithm journal`
* *List* : `list`
* *Help* : `help`
* *Biblio* : `biblio`
* *History* : `history`
* *Search History* : `searchhistory`
* *Define Command* : `definecommand c/COMMAND a/ALIAS` +
e.g. `definecommand c/edit a/e`
* *Undo* : `undo`
* *Redo* : `redo`
* *Panic* : `panic`
* *Unpanic* : `unpanic`
